extends: default

rules:
    line-length:
        max: 150
        ignore: |
            *-lock.yaml
    document-start: disable
    truthy:
        check-keys: false
    comments:
        min-spaces-from-content: 1
    braces:
        max-spaces-inside: 1
