name: Setup and Build
description: Install tools, dependencies, sync, build, and optionally package artifact
inputs:
    package:
        description: 'Whether to create build-artifact.zip'
        required: false
        default: 'true'
runs:
    using: 'composite'
    steps:
        - name: Checkout repository
          uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
          with:
              fetch-depth: 0

        - name: Install mise
          uses: jdx/mise-action@f8dfbcc150159126838e44b882bf34bd98fd90f3 # v2.1.0
          with:
              install_args: --yes

        - name: Install dependencies
          shell: bash
          run: mise run install

        - name: Sync SvelteKit
          shell: bash
          run: mise run sync

        - name: Build static site
          shell: bash
          run: mise run build

        - name: Package artifact
          if: ${{ inputs.package == 'true' }}
          shell: bash
          run: |
              cd build
              zip -r ../build-artifact.zip .
              cd ..
              du -h build-artifact.zip | cut -f1 > .artifact_size

        - name: Export artifact size
          if: ${{ inputs.package == 'true' }}
          id: pkg
          shell: bash
          run: echo "size=$(cat .artifact_size)" >> "$GITHUB_OUTPUT"
